### PR TITLE
Deploy kafka-ui API (exist a bug related to ingress)

### PR DESCRIPTION
**Pull request by Haoyuan-L**
Able to debug the kafka with kafka-ui, following the deployments and login in the GUI with 127.0.0.1:8088
kafka-ui

### CODE REVIEW

**Comment by benblamey** [comment]
fixes: https://github.com/HASTE-project/hom-2/issues/19

**Comment by Haoyuan-L** [comment]
> looks great!
> 
> Can you also add some instructions to the readme for the port forwarding?

of course

**Comment by benblamey** [comment]
https://github.com/HASTE-project/hom-2/pull/31

**Comment by benblamey** [comment]
See https://github.com/HASTE-project/hom-2/pull/31 instead

**Pull request closed without merging**
